# The Docker image to run your workspace in. Defaults to gitpod/workspace-full
image:
  file: 
    .gitpod.Dockerfile

# Ports to expose on workspace startup (optional)
ports:
  - port: 8080
    onOpen: open-preview



tasks:
  - before: airflow scheduler
  - command: echo nitialize the database
  - init: airflow initdb
  - command: echo start the web server, default port is 8080
  - command: airflow webserver -p 8080
  - command: echo start the scheduler